In [19]:
import pandas as pd

In [30]:
df = pd.read_csv('data/disney_plus_shows.csv')

In [21]:
df.head

<bound method NDFrame.head of        imdb_id                                       title  \
0    tt0147800                  10 Things I Hate About You
1    tt7019028                        101 Dalmatian Street
2    tt0115433                              101 Dalmatians
3    tt0324941  101 Dalmatians 2: Patch's London Adventure
4    tt0211181                              102 Dalmatians
..         ...                                         ...
987  tt3544734                                      Zapped
988  tt0186726             Zenon: Girl of the 21st Century
989  tt0271271                           Zenon: The Zequel
990  tt0379060                                   Zenon: Z3
991  tt2948356                                    Zootopia

                                                  plot    type  rated   year  \
0    A pretty, popular teenager can't go out on a d...   movie  PG-13   1999
1    This series follows the lives of Delilah and D...  series    NaN  2018–
2    An evil high-fashion designer plots to steal D...   movie      G   1996
3    Being one of 101 takes its toll on Patch, who ...   movie      G   2002
4    Cruella DeVil gets out of prison and goes afte...   movie      G   2000
..                                                 ...     ...    ...    ...
987  When Zoey's mom remarries, Zoey finds it hard ...   movie   TV-G   2014
988  An inquisitive teenager pries into suspected d...   movie   TV-G   1999
989  A mischievous fifteen-year-old girl living on ...   movie   TV-G   2001
990  The heroine sets out to win an important compe...   movie   TV-G   2004
991  In a city of anthropomorphic animals, a rookie...   movie     PG   2016

     released_at           added_at  runtime  \
0    31 Mar 1999  November 12, 2019   97 min
1    25 Mar 2019  February 28, 2020      NaN
2    27 Nov 1996  November 12, 2019  103 min
3    21 Jan 2003  November 12, 2019   74 min
4    22 Nov 2000  November 12, 2019  100 min
..           ...                ...      ...
987  23 Jun 2014  November 12, 2019  102 min
988  23 Jan 1999  November 12, 2019   97 min
989  12 Jan 2001  November 12, 2019  100 min
990  11 Jun 2004  November 12, 2019   81 min
991  04 Mar 2016  November 12, 2019  108 min

                                                 genre  \
0                               Comedy, Drama, Romance
1                            Animation, Comedy, Family
2                     Adventure, Comedy, Crime, Family
3        Animation, Adventure, Comedy, Family, Musical
4                            Adventure, Comedy, Family
..                                                 ...
987                            Comedy, Family, Fantasy
988                  Adventure, Comedy, Family, Sci-Fi
989                  Comedy, Family, Adventure, Sci-Fi
990                  Adventure, Comedy, Family, Sci-Fi
991  Animation, Adventure, Comedy, Crime, Family, M...

                                              director  \
0                                           Gil Junger
1                                                  NaN
2                                        Stephen Herek
3                            Jim Kammerud, Brian Smith
4                                           Kevin Lima
..                                                 ...
987                                      Peter DeLuise
988                                    Kenneth Johnson
989                                         Manny Coto
990                                         Steve Rash
991  Byron Howard, Rich Moore, Jared Bush(co-director)

                                                writer  \
0                        Karen McCullah, Kirsten Smith
1                                                  NaN
2        Dodie Smith (novel), John Hughes (screenplay)
3    Jim Kammerud (story), Dan Root (story), Garret...
4    Dodie Smith (novel), Kristen Buckley (story), ...
..                                                 ...
987  Leslie Margolis (based on the novel "Boys Are ...
988  Marilyn Sadler (book), Roger Bollen (book), St...
989  Marilyn Sadler (book), Roger Bollen (book), St...
990  Marilyn Sadler (character from the book "Zenon...
991  Byron Howard (story by), Rich Moore (story by)...

                                                actors          language  \
0    Heath Ledger, Julia Stiles, Joseph Gordon-Levi...   English, French
1    Josh Brener, Michaela Dietz, Bert Davis, Abiga...           English
2    Glenn Close, Jeff Daniels, Joely Richardson, J...  English, Spanish
3    Barry Bostwick, Jason Alexander, Martin Short,...           English
4    Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...           English
..                                                 ...               ...
987  Zendaya, Chanelle Peloso, Spencer Boldman, Emi...           English
988  Kirsten Storms, Raven-Symoné, Stuart Pankin, H...           English
989  Kirsten Storms, Shadia Simmons, Lauren Maltby,...           English
990  Kirsten Storms, Lauren Maltby, Alyson Morgan, ...           English
991  Ginnifer Goodwin, Jason Bateman, Idris Elba, J...           English

              country                                             awards  \
0                 USA                           2 wins & 13 nominations.
1     UK, USA, Canada                                                NaN
2             USA, UK  Nominated for 1 Golden Globe. Another 3 wins &...
3                 USA                           5 wins & 10 nominations.
4             USA, UK  Nominated for 1 Oscar. Another 1 win & 7 nomin...
..                ...                                                ...
987       Canada, USA                             5 wins & 1 nomination.
988               USA                                     2 nominations.
989  USA, New Zealand                                      1 nomination.
990               USA                                                NaN
991               USA     Won 1 Oscar. Another 46 wins & 71 nominations.

     metascore  imdb_rating imdb_votes
0         70.0          7.3    283,945
1          NaN          6.2        124
2         49.0          5.7     97,785
3          NaN          5.8      7,434
4         35.0          4.9     33,444
..         ...          ...        ...
987        NaN          5.1      3,750
988        NaN          6.4      6,378
989        NaN          5.9      3,318
990        NaN          5.5      2,339
991       78.0          8.0    410,437

[992 rows x 19 columns]>

In [7]:
df.head(10)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"
5,tt1846442,12 Dates of Christmas,"A story that follows Kate, a young woman who a...",movie,PG,2011,11 Dec 2011,"November 12, 2019",90 min,"Comedy, Fantasy, Romance",James Hayman,"Aaron Mendelsohn (teleplay), Janet Brownell (t...","Laura Miyata, Vijay Mehta, Amy Smart, Audrey D...",English,USA,1 nomination.,NaN,6.3,"4,933"
6,tt0046672,"20,000 Leagues Under the Sea",A ship sent to investigate a wave of mysteriou...,movie,G,1954,20 Jul 1955,"November 12, 2019",127 min,"Adventure, Drama, Family, Fantasy, Sci-Fi",Richard Fleischer,Earl Felton (screenplay),"Kirk Douglas, James Mason, Paul Lukas, Peter L...",English,USA,Won 2 Oscars. Another 3 wins & 3 nominations.,83.0,7.2,"27,761"
7,tt0120623,A Bug's Life,"A misfit ant, looking for ""warriors"" to save h...",movie,G,1998,25 Nov 1998,"November 12, 2019",95 min,"Animation, Adventure, Comedy, Family","John Lasseter, Andrew Stanton(co-director)","John Lasseter (original story by), Andrew Stan...","Dave Foley, Kevin Spacey, Julia Louis-Dreyfus,...",English,USA,Nominated for 1 Oscar. Another 14 wins & 20 no...,77.0,7.2,"257,065"
8,tt12076020,A Celebration of the Music from Coco,NaN,movie,NaN,2020,10 Apr 2020,"April 10, 2020",NaN,Music,Ron de Moraes,NaN,"Benjamin Bratt, Eva Longoria",English,USA,NaN,NaN,7.6,35
9,tt0113198,A Goofy Movie,When Max makes a preposterous promise to a gir...,movie,G,1995,07 Apr 1995,"November 12, 2019",78 min,"Animation, Adventure, Comedy, Family, Musical,...",Kevin Lima,"Jymn Magon (story), Jymn Magon (screenplay), C...","Bill Farmer, Jason Marsden, Jim Cummings, Kell...",English,"USA, Australia, France, Canada",5 nominations.,NaN,6.8,"43,655"

In [22]:
df.columns.tolist()

['imdb_id',
 'title',
 'plot',
 'type',
 'rated',
 'year',
 'released_at',
 'added_at',
 'runtime',
 'genre',
 'director',
 'writer',
 'actors',
 'language',
 'country',
 'awards',
 'metascore',
 'imdb_rating',
 'imdb_votes']

In [31]:
df['unique_actors']=df['actors']

In [32]:
df['unique_actors']=df['unique_actors'].str.split(",")

In [33]:
df=df.explode('unique_actors')

In [34]:
df['unique_actors']=df['unique_actors'].str.strip()

In [36]:
df[['unique_actors','imdb_rating']].head(10)

          unique_actors  imdb_rating
0          Heath Ledger          7.3
0          Julia Stiles          7.3
0  Joseph Gordon-Levitt          7.3
0        Larisa Oleynik          7.3
1           Josh Brener          6.2
1        Michaela Dietz          6.2
1            Bert Davis          6.2
1     Abigail Zoe Lewis          6.2
2           Glenn Close          5.7
2          Jeff Daniels          5.7

In [37]:
df=df[df['type'] == 'movie']

In [38]:
df.groupby('unique_actors')['imdb_rating']

In [42]:
df.groupby('unique_actors')['imdb_rating'].mean()

unique_actors
A.J. Langer             4.10
A.J. Trauth             6.10
AJ Michalka             5.20
Aaron Michael Drozin    5.30
Adam Driver             7.45
                        ...
Zendaya                 5.05
Zhong Yu                6.40
Zoe Saldana             7.80
Zooey Deschanel         6.40
Émile Genest            7.10
Name: imdb_rating, Length: 1641, dtype: float64

In [44]:
df.groupby('unique_actors')['imdb_rating'].count()

unique_actors
A.J. Langer             1
A.J. Trauth             1
AJ Michalka             1
Aaron Michael Drozin    1
Adam Driver             2
                       ..
Zendaya                 2
Zhong Yu                1
Zoe Saldana             3
Zooey Deschanel         1
Émile Genest            1
Name: imdb_rating, Length: 1641, dtype: int64

In [46]:
df.groupby('unique_actors')['imdb_rating'].agg(['mean','count'])

                      mean  count
unique_actors
A.J. Langer           4.10      1
A.J. Trauth           6.10      1
AJ Michalka           5.20      1
Aaron Michael Drozin  5.30      1
Adam Driver           7.45      2
...                    ...    ...
Zendaya               5.05      2
Zhong Yu              6.40      1
Zoe Saldana           7.80      3
Zooey Deschanel       6.40      1
Émile Genest          7.10      1

[1641 rows x 2 columns]

In [48]:
actors_stats = df.groupby('unique_actors')['imdb_rating'].agg(['mean', 'count'])

In [51]:
actors_stats.head()

                      mean  count
unique_actors
A.J. Langer           4.10      1
A.J. Trauth           6.10      1
AJ Michalka           5.20      1
Aaron Michael Drozin  5.30      1
Adam Driver           7.45      2

In [52]:
actors_stats.loc[actors_stats['count'] > 1 ]

                       mean  count
unique_actors
Adam Driver        7.450000      2
Adrienne Houghton  4.833333      3
Alan Young         7.500000      2
Albert Brooks      7.700000      2
Alex D. Linz       5.100000      2
...                     ...    ...
Winston Hibler     7.480000     10
Zac Efron          5.066667      3
Zachary Levi       7.150000      2
Zendaya            5.050000      2
Zoe Saldana        7.800000      3

[397 rows x 2 columns]

In [55]:
actors_stats_filtered = actors_stats.loc[actors_stats['count'] > 1]

actors_stats_filtered = actors_stats_filtered.sort_values('mean', ascending=False)

In [56]:
actors_stats_filtered.head(10)

                      mean  count
unique_actors
Billy Dee Williams   8.500      2
Harrison Ford        8.375      4
Tony Fucile          8.100      2
Christopher Plummer  8.100      2
Carrie Fisher        8.100      5
Mark Hamill          8.100      5
Chris Sarandon       8.050      2
Benjamin Bratt       8.000      2
Idris Elba           7.950      2
Hal Smith            7.950      2

In [59]:
actors_stats_filtered.rename(columns = {
    'mean': 'average_imdb_rating',
    'count': 'number_of_movies'
    }
)

                     average_imdb_rating  number_of_movies
unique_actors
Billy Dee Williams              8.500000                 2
Harrison Ford                   8.375000                 4
Tony Fucile                     8.100000                 2
Christopher Plummer             8.100000                 2
Carrie Fisher                   8.100000                 5
...                                  ...               ...
Thomas Haden Church             4.350000                 2
Joe Jonas                       3.966667                 3
Kevin Jonas                     3.350000                 2
Nick Jonas                      3.350000                 2
Billy Ray Cyrus                 3.350000                 2

[397 rows x 2 columns]

In [64]:
#Task 2

In [61]:
awards_df = pd.read_csv('data/disney_plus_shows.csv')

In [65]:
awards_df = awards_df[awards_df['type'] == 'movie'].copy()

In [66]:
awards_df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"
5,tt1846442,12 Dates of Christmas,"A story that follows Kate, a young woman who a...",movie,PG,2011,11 Dec 2011,"November 12, 2019",90 min,"Comedy, Fantasy, Romance",James Hayman,"Aaron Mendelsohn (teleplay), Janet Brownell (t...","Laura Miyata, Vijay Mehta, Amy Smart, Audrey D...",English,USA,1 nomination.,NaN,6.3,"4,933"

In [79]:
awards_df['special_wins'] = awards_df['awards'].str.extract(r'Won (\d+)', expand=False)
awards_df['special_nominations'] = awards_df['awards'].str.extract(r'Nominated for (\d+)',expand=False)

In [80]:
awards_df['wins'] = awards_df['awards'].str.extract(r'(\d+) wins?',expand=False)
awards_df['nominations'] = awards_df['awards'].str.extract(r'(\d+) nominations?',expand=False)

In [85]:
awards_df['wins'] = awards_df['wins'].fillna(0).astype(int)
awards_df['nominations'] = awards_df['nominations'].fillna(0).astype(int)
awards_df['special_wins'] = awards_df['special_wins'].fillna(0).astype(int)
awards_df['special_nominations'] = awards_df['special_nominations'].fillna(0).astype(int)

In [88]:
awards_df[['special_wins','wins','special_nominations','nominations']]

     special_wins  wins  special_nominations  nominations
0               0     2                    0           13
2               0     3                    1            9
3               0     5                    0           10
4               0     1                    1            7
5               0     0                    0            1
..            ...   ...                  ...          ...
987             0     5                    0            1
988             0     0                    0            2
989             0     0                    0            1
990             0     0                    0            0
991             1    46                    0           71

[680 rows x 4 columns]

In [89]:
awards_df.info()

<class 'pandas.DataFrame'>
Index: 680 entries, 0 to 991
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   imdb_id              680 non-null    str
 1   title                680 non-null    str
 2   plot                 664 non-null    str
 3   type                 680 non-null    str
 4   rated                598 non-null    str
 5   year                 680 non-null    str
 6   released_at          676 non-null    str
 7   added_at             680 non-null    str
 8   runtime              662 non-null    str
 9   genre                676 non-null    str
 10  director             670 non-null    str
 11  writer               618 non-null    str
 12  actors               665 non-null    str
 13  language             669 non-null    str
 14  country              678 non-null    str
 15  awards               433 non-null    str
 16  metascore            292 non-null    float64
 17  imdb_rating          676 non-null    float64
 18  imdb_votes           676 non-null    str
 19  wins                 680 non-null    int64
 20  nominations          680 non-null    int64
 21  oscars               125 non-null    str
 22  golden_globes        0 non-null      str
 23  special_wins         680 non-null    int64
 24  special_nominations  680 non-null    int64
dtypes: float64(2), int64(4), str(19)
memory usage: 438.5 KB

In [91]:
awards_per_movie_df=awards_df[
    ['imdb_id','title','wins','special_wins','nominations','special_nominations']
    ]

In [92]:
awards_per_movie_df.info()

<class 'pandas.DataFrame'>
Index: 680 entries, 0 to 991
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   imdb_id              680 non-null    str
 1   title                680 non-null    str
 2   wins                 680 non-null    int64
 3   special_wins         680 non-null    int64
 4   nominations          680 non-null    int64
 5   special_nominations  680 non-null    int64
dtypes: int64(4), str(2)
memory usage: 55.8 KB

In [93]:
awards_per_movie_df.head()

,imdb_id,title,wins,special_wins,nominations,special_nominations
0,tt0147800,10 Things I Hate About You,2,0,13,0
2,tt0115433,101 Dalmatians,3,0,9,1
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,5,0,10,0
4,tt0211181,102 Dalmatians,1,0,7,1
5,tt1846442,12 Dates of Christmas,0,0,1,0

In [95]:
awards_per_movie_df['total_wins'] = awards_per_movie_df['wins'] + awards_per_movie_df['special_wins']
awards_per_movie_df['total_nominations'] = awards_per_movie_df['nominations'] + awards_per_movie_df['special_nominations']

In [98]:
awards_per_movie_df = awards_per_movie_df.sort_values(['total_wins','total_nominations'], ascending = [False, False])

In [101]:
awards_per_movie_df = awards_per_movie_df[
    [
        'imdb_id',
        'title',
        'total_wins',
        'total_nominations',
        'wins',
        'special_wins',
        'nominations',
        'special_nominations'
    ]
]

In [102]:
awards_per_movie_df.head(30)

,imdb_id,title,total_wins,total_nominations,wins,special_wins,nominations,special_nominations
487,tt1825683,Black Panther,111,265,108,3,265,0
128,tt2380307,Coco,110,36,108,2,36,0
382,tt2096673,Inside Out,98,114,97,1,114,0
956,tt0910970,WALL·E,92,93,91,1,93,0
40,tt0499549,Avatar,89,129,86,3,129,0
301,tt2294629,Frozen,81,59,79,2,59,0
950,tt1049413,Up,80,82,78,2,82,0
811,tt0317705,The Incredibles,67,56,65,2,56,0
639,tt0382932,Ratatouille,67,42,66,1,42,0
486,tt4154796,Avengers: Endgame,64,103,64,0,102,1
720,tt2488496,Star Wars: Episode VII - The Force Awakens,62,130,62,0,125,5
925,tt0435761,Toy Story 3,62,95,60,2,95,0
712,tt0076759,Star Wars: Episode IV - A New Hope,58,28,52,6,28,0
493,tt2015381,Guardians of the Galaxy,52,102,52,0,100,2
273,tt0266543,Finding Nemo,50,62,49,1,62,0
926,tt1979376,Toy Story 4,50,53,49,1,53,0
991,tt2948356,Zootopia,47,71,46,1,71,0
610,tt0383574,Pirates of the Caribbean: Dead Man's Chest,44,53,43,1,53,0
612,tt0325980,Pirates of the Caribbean: The Curse of the Bla...,38,103,38,0,98,5
498,tt0848228,The Avengers,38,80,38,0,79,1
821,tt0110357,The Lion King,37,34,35,2,34,0
396,tt7207238,Jane,36,37,34,2,37,0
20,tt1014759,Alice in Wonderland,35,63,33,2,63,0
978,tt1772341,Wreck-It Ralph,33,42,33,0,41,1
16,tt0103639,Aladdin,33,22,31,2,22,0
299,tt7775622,Free Solo,30,54,29,1,54,0
50,tt0101414,Beauty and the Beast,29,34,27,2,34,0
98,tt0317219,Cars,28,34,28,0,32,2
923,tt0114709,Toy Story,27,23,27,0,20,3
722,tt0120915,Star Wars: Episode I - The Phantom Menace,26,68,26,0,65,3

In [104]:
awards_per_movie_df['imdb_rating']=awards_df['imdb_rating']

In [106]:
awards_per_movie_df['total_wins'].corr(awards_per_movie_df['imdb_rating'])

np.float64(0.3358964558380018)

In [107]:
awards_per_movie_df['metascore']=awards_df['metascore']

In [108]:
awards_per_movie_df['total_wins'].corr(awards_per_movie_df['metascore'])

np.float64(0.4934826194934425)